POST http://localhost:3001/api/patients
content-type: application/json

{
        "name": "Roosevelt Kessler",
        "dateOfBirth": "1993-11-09",
        "ssn": "235435-101X",
        "gender": "male",
        "occupation": "student",
        "healthRating": 4
}